on:
  push:
    branches:
    - main
    - master
    - release/*
  pull_request:
    branches:
    - main
jobs:
  validation:
    strategy:
      fail-fast: false
      matrix:
        # LTS JDK active one year before if still active, current active LTS JDK, active normal JDKs in the last 12 months
        jdkVer: [ 17, 21, 22, 23 ]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Gradle Wrapper Validation
      uses: gradle/actions/wrapper-validation@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: ${{ matrix.jdkVer }}
    # Intentionally don't use Gradle Action
    # as its caching would make it harder to verify Gradle build under different JDKs

    - name: Build
      run: ./gradlew installDist
